name: i_anda_rm2

on:
  workflow_dispatch:    # Manual run
  schedule:             # Automatic re-run every 6 hours
    - cron: "0 */6 * * *"  # At minute 0, every 6th hour

concurrency:
  group: i_anda_rm2
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Unzip pocketoptionapi
      run: |
        unzip pocketoptionapi.zip -d ./

    - name: Run the bot
      env:
        OANDA_TOKEN: ${{ secrets.OANDA_TOKEN }}
        OANDA_ID: ${{ secrets.OANDA_ID }}
        PO_SSID: ${{ secrets.PO_SSID }}
      run: |
        python main_rm.py
